@startuml change-deadline
hide unlinked
!include ../generic-blocks.plantuml

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant HomePage <</>>
participant ElectoralRegisterDashPage <</electoral-register>>
participant ChangeDeadlinePage <</electoral-register/change-deadline>>
participant GenericErrorPage <</error>>

''' CONTROLLER AND REQUEST OBJECTS
participant ChangeDeadlineController <<change-deadline.controller.js>> #lightyellow
participant SetDeadlineController <<set-deadline.controller.js>> #lightyellow
participant ErDeadlineDAO <<erDeadlineDAO.put()>> #lightyellow

''' FILTERS AND VALIDATORS
participant NonAttendanceDayValidator as Validator

''' TEMPLATES
participant ChangeDeadlineTemplate <<electoral-register/change-deadline.njk>> #lavender
participant ErrorTemplate <<_errors/generic.njk>> #lavender

''' BACKEND CONTROLLER
participant BackendController

Actor -> ElectoralRegisterDashPage : Click "Change deadline" link
ElectoralRegisterDashPage -> ChangeDeadlineController : call page controller

$renderTemplateToPage(ChangeDeadlineController, ChangeDeadlineTemplate, ChangeDeadlinePage)

Actor -> ChangeDeadlinePage : Select a date and click "Change deadline" button
ChangeDeadlinePage -> ChangeDeadlineController : call change deadline controller
ChangeDeadlineController -> SetDeadlineController : call set deadline controller to update the deadline

$validateInput(SetDeadlineController, Validator, ChangeDeadlineTemplate, ChangeDeadlinePage, "Invalid input")

$genericAPICall(SetDeadlineController, ErDeadlineDAO, ErrorTemplate, "Error setting deadline")

ElectoralRegisterDashPage <- SetDeadlineController : redirect to dashboard page
Actor <- ElectoralRegisterDashPage : view updated deadline on dashboard

@enduml    