@startuml add-default-expenses
hide unlinked
!include generic-blocks.plantuml

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant JurorRecordExpensesPage <</juror-management/record/:jurorNumber/expenses>>
participant DraftExpenseRecordPage <</juror-management/unpaid-attendance/expense-record/:jurorNumber/:poolNumber>>
participant DefaultExpensesPage <</juror-management/expenses/:jurorNumber/:poolNumber/default-expenses>>
participant GenericErrorPage <</error>>

''' CONTROLLER AND REQUEST OBJECTS
participant JurorRecordController <<juror-record.controller.js>> #lightyellow
participant ExpenseRecordController <<expense-record.controller.js>> #lightyellow
participant DefaultExpensesController <<expenses.controller.js>> #lightyellow
participant DefaultExpensesObject <<defaultExpensesDAO.get()>> #lightyellow
participant SetDefaultExpensesObject <<defaultExpensesDAO.post()>> #lightyellow

''' TEMPLATES
participant JurorRecordExpensesTemplate <<juror-management/juror-record/expenses.njk>> #lavender
participant DraftExpenseRecordTemplate <<juror-management/expense-record/expense-record.njk>> #lavender
participant DefaultExpensesTemplate <<expenses/default-expenses.njk>> #lavender
participant ErrorTemplate <<_errors/generic.njk>> #lavender

''' FILTERS AND VALIDATORS
participant DefaultExpensesValidator

''' BACKEND CONTROLLER
participant BackendController

group Navigate from juror record
  Actor -> JurorRecordExpensesPage : click add or change default expenses link
  JurorRecordExpensesPage -> DefaultExpensesController : call expenses controller
else Navigate from expense record
  Actor -> DraftExpenseRecordPage : click add or change default expenses link
  DraftExpenseRecordPage -> DefaultExpensesController : call expenses controller
end

$genericAPICall(DefaultExpensesController, DefaultExpensesObject, ErrorTemplate, "Failed to fetch jurors default expenses")
 
$renderTemplateToPage(DefaultExpensesController, DefaultExpensesTemplate, DefaultExpensesPage)

Actor -> DefaultExpensesPage : enters a valid default expense values
DefaultExpensesPage -> DefaultExpensesController : call page controller

$validateInput(DefaultExpensesController, DefaultExpensesValidator, DefaultExpensesTemplate, DefaultExpensesPage, "Invalid values entered")

$genericAPICall(DefaultExpensesController, SetDefaultExpensesObject, ErrorTemplate, "Failed to set default expenses")

group Initally navigated from juror record
  DefaultExpensesController -> JurorRecordController : call juror record controller controller
  $renderTemplateToPage(JurorRecordController, JurorRecordExpensesTemplate, JurorRecordExpensesPage)
else Initally navigated from expense record
  DefaultExpensesController -> ExpenseRecordController : call juror record controller controller
  $renderTemplateToPage(ExpenseRecordController, DraftExpenseRecordTemplate, DraftExpenseRecordPage)
end

@enduml    