@startuml add-smartcard-spend
hide unlinked
!include generic-blocks.plantuml

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant ExpenseRecordPage <</juror-management/unpaid-attendance/expense-record/:jurorNumber/:poolNumber>>
participant AddSmartcardSpendPage <<//juror-management/unpaid-attendance/expense-record/:jurorNumber/:poolNumber/add-smartcard-spend>>
''' CONTROLLER AND REQUEST OBJECTS
participant AddSmartcardSpendController <<add-smartcard-spend.controller.js>> #lightyellow
participant AddSmartcardSpendObject <<addSmartcardSpend.patch()>> #lightyellow

''' TEMPLATES
participant AddSmartcardSpendTemplate <<juror-management/expense-record/add-smartcard-spend.njk>> #lavender

''' FILTERS AND VALIDATORS
participant SmartcardSpendValidator

''' BACKEND CONTROLLER
participant BackendController

Actor -> ExpenseRecordPage : click add smartcard spend link
ExpenseRecordPage -> AddSmartcardSpendController : call smartcard spend controller

$renderTemplateToPage(AddSmartcardSpendController, AddSmartcardSpendTemplate, AddSmartcardSpendPage)

Actor -> AddSmartcardSpendPage : enters valid expense values

AddSmartcardSpendPage -> AddSmartcardSpendController : call page controller

$validateInput(AddSmartcardSpendController, SmartcardSpendValidator, AddSmartcardSpendTemplate, AddSmartcardSpendPage, "Invalid values entered")

$genericAPICall(AddSmartcardSpendController, AddSmartcardSpendObject, AddSmartcardSpendTemplate, "Failed to update the smart card amount for all selected days")

AddSmartcardSpendController -> ExpenseRecordPage : redirect to expense record page
Actor <- ExpenseRecordPage : render expense record page

@enduml