@startuml add-non-attendance-day
hide unlinked
!include generic-blocks.plantuml

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant JurorRecordAttendancePage <</juror-management/record/:jurorNumber/attendance>>
participant DraftExpenseRecordPage <</juror-management/unpaid-attendance/expense-record/:jurorNumber/:poolNumber>>
participant AddNonAttendanceDayPage <</juror-management/unpaid-attendance/non-attendance-day/:jurorNumber/:poolNumber>>
participant GenericErrorPage <</error>>

''' CONTROLLER AND REQUEST OBJECTS
participant JurorRecordController <<juror-record.controller.js>> #lightyellow
participant ExpenseRecordController <<expense-record.controller.js>> #lightyellow
participant NonAttendanceDayController <<non-attendance-day.controller.js>> #lightyellow
participant NonAttendanceDayObject <<jurorNonAttendanceDao.post()>> #lightyellow

''' TEMPLATES
participant JurorRecordAttendanceTemplate <<juror-management/juror-record/attendance.njk>> #lavender
participant DraftExpenseRecordTemplate <<juror-management/expense-record/expense-record.njk>> #lavender
participant NonAttendanceDayTemplate <<juror-management/non-attendance-day.njk>> #lavender
participant ErrorTemplate <<_errors/generic.njk>> #lavender

''' FILTERS AND VALIDATORS
participant NonAttendanceDayValidator

''' BACKEND CONTROLLER
participant BackendController

group Navigate from juror record
  Actor -> JurorRecordAttendancePage : click add non-attendance day
  JurorRecordAttendancePage -> NonAttendanceDayController : call non-attendance day controller
else Navigate from expense record
  Actor -> DraftExpenseRecordPage : click add non-attendance day
  DraftExpenseRecordPage -> NonAttendanceDayController : call non-attendance day conrtoller
end

$renderTemplateToPage(NonAttendanceDayController, NonAttendanceDayTemplate, AddNonAttendanceDayPage)

Actor -> AddNonAttendanceDayPage : enters a valid non-attendance day and clicks continue

AddNonAttendanceDayPage -> NonAttendanceDayController : call page controller

$validateInput(NonAttendanceDayController, NonAttendanceDayValidator, NonAttendanceDayTemplate, AddNonAttendanceDayPage, "Invalid date entered")

NonAttendanceDayController -> NonAttendanceDayObject : build request object
NonAttendanceDayObject -> BackendController : send backend request

$APIErrorAlt(NonAttendanceDayController, NonAttendanceDayObject, errorTemplate, "Error 422 - Business Rule Violation", NonAttendanceDayTemplate, AddNonAttendanceDayPage)

$APIErrorAlt(NonAttendanceDayController, NonAttendanceDayObject, ErrorTemplate, "Failed to add a non-attendance day for juror(s)")

NonAttendanceDayObject <- BackendController : ok response
NonAttendanceDayController <- NonAttendanceDayObject : resolve request

group Initally navigated from juror record
  NonAttendanceDayController -> JurorRecordController : call juror record controller controller
  $renderTemplateToPage(JurorRecordController, JurorRecordAttendanceTemplate, JurorRecordAttendancePage)
else Initally navigated from expense record
  NonAttendanceDayController -> ExpenseRecordController : call juror record controller controller
  $renderTemplateToPage(ExpenseRecordController, DraftExpenseRecordTemplate, DraftExpenseRecordPage)
end

@enduml    