@startuml bulk-change-next-due-at-court
hide unlinked
!include generic-blocks.plantuml

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant PoolOverviewPage <</pool-management/pool-overview/:poolNumber>>
participant ChangeNextDueAtCourtPage <</pool-management/:poolNumber/change-next-due-at-court/continue>>
participant ChangeNextDueAtCourtConfirmationPage <</pool-management/:poolNumber/change-next-due-at-court/confirm>>
participant GenericErrorPage <</error>>

''' CONTROLLER AND REQUEST OBJECTS
participant PoolOverviewController <<pool-overview.controller.js>>
participant ChangeNextDueAtCourtController <<change-next-due-at-court.controller.js>>
participant PoolMembersObject <<poolMembersDAO.post()>>
participant ChangeNextDueAtCourtObject <<changeNextDueAtCourtDAO.patch()>>

''' TEMPLATES
participant PoolOverviewTemplate <<pool-management/pool-overview/{bureau/court}-pool-overview.njk>>
participant ChangeNextDueAtCourtTemplate <<pool-management/change-next-due-at-court/change-next-due-at-court.njk>>
participant ChangeNextDueAtCourtConfirmationTemplate <<pool-management/change-next-due-at-court/confirm-next-due-at-court.njk>>
participant ErrorTemplate <<_errors/generic.njk>>

''' FILTERS AND VALIDATORS
participant JurorSelectValidator
participant AttendanceDateValidator

''' BACKEND CONTROLLER
participant BackendController


''' JOURNEY FLOW
Actor -> PoolOverviewPage : User selects one or more jurors and clicks 'Change next due at court'
PoolOverviewPage -> PoolOverviewController : call page controller

alt User clicks 'Check all' checkbox
  $genericAPICall(PoolOverviewController, PoolMembersObject, ErrorTemplate, "Failed to fetch pool members to change next due at court date")
end

$validateInput(PoolOverviewController, JurorSelectValidator, PoolOverviewTemplate, PoolOverviewPage)

$renderTemplateToPage(PoolOverviewController, ChangeNextDueAtCourtTemplate, ChangeNextDueAtCourtPage)

Actor -> ChangeNextDueAtCourtPage : User selects a date and clicks 'Continue'
ChangeNextDueAtCourtPage -> ChangeNextDueAtCourtController : call page controller
$validateInput(ChangeNextDueAtCourtController, ChangeNextDueAtCourtValidator, ChangeNextDueAtCourtTemplate, ChangeNextDueAtCourtPage)

$renderTemplateToPage(ChangeNextDueAtCourtController, ChangeNextDueAtCourtConfirmationTemplate, ChangeNextDueAtCourtConfirmationPage)
Actor -> ChangeNextDueAtCourtConfirmationPage : User clicks 'Continue'
ChangeNextDueAtCourtConfirmationPage -> ChangeNextDueAtCourtController : call page controller
$genericAPICall(ChangeNextDueAtCourtController, ChangeNextDueAtCourtObject, ErrorTemplate, "Failed to change attendance dates for juror(s)")

PoolOverviewController <- ChangeNextDueAtCourtController : redirect to pool overview
PoolOverviewPage <- PoolOverviewController : redirect to pool overview
Actor <- PoolOverviewPage : render pool overview page with success banner

@enduml