@startuml bulk-complete-service
hide unlinked
!include generic-blocks.plantuml

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant PoolOverviewPage <</pool-management/pool-overview/:poolNumber>>
participant CompleteServicePage <</pool-management/:poolNumber/complete-service/confirm>>
participant GenericErrorPage <</error>>

''' CONTROLLER AND REQUEST OBJECTS
participant PoolOverviewController <<pool-overview.controller.js>>
participant CompleteServiceController <<complete-service.controller.js>>
participant PoolMembersObject <<poolMembersDAO.post()>>
participant CompleteServiceObject <<completeServiceDAO.patch()>>

''' TEMPLATES
participant PoolOverviewTemplate <<pool-management/pool-overview/{bureau/court}-pool-overview.njk>>
participant CompleteServiceTemplate <<shared/complete-service/complete-service-confirm.njk>>
participant ErrorTemplate <<_errors/generic.njk>>

''' FILTERS AND VALIDATORS
participant CompleteServiceValidator

''' BACKEND CONTROLLER
participant BackendController


''' JOURNEY FLOW
Actor -> PoolOverviewPage : User selects one or more jurors and clicks 'Complete service'
PoolOverviewPage -> PoolOverviewController : call page controller

alt User clicks 'Check all' checkbox
  $genericAPICall(PoolOverviewController, PoolMembersObject, ErrorTemplate, "Failed to fetch pool members for complete service")
end

alt no jurors selected
 $renderErrorOnForm(PoolOverviewController, PoolOverviewTemplate, PoolOverviewPage)
end

PoolOverviewController -> CompleteServiceController : pass control to complete service controller

$renderTemplateToPage(CompleteServiceController, CompleteServiceTemplate, CompleteServicePage)

Actor -> CompleteServicePage : User selects completion date and clicks 'Complete service'
CompleteServicePage -> CompleteServiceController : call page controller
$validateInput(CompleteServiceController, CompleteServiceValidator, CompleteServiceTemplate, CompleteServicePage)
$callAPIRenderErrorOnForm(CompleteServiceController, CompleteServiceObject, ErrorTemplate, "Failed to complete juror(s) service", PoolOverviewTemplate, PoolOverviewPage, PoolOverviewController)

PoolOverviewController <- CompleteServiceController : redirect to pool overview
PoolOverviewPage <- PoolOverviewController : redirect to pool overview
Actor <- PoolOverviewPage : render pool overview page with success banner

@enduml