@startuml dismiss-jurors
hide unlinked
!include generic-blocks.plantuml

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant PoolManagementPage <</pool-management>>
participant DismissJurorsPoolsPage <</pool-management/dismiss-jurors/pools>>
participant DismissJurorsSelectPage <</pool-management/dismiss-jurors/jurors>>
participant CheckOutJurorsPage <</pool-management/dismiss-jurors/check-out>>
participant CompleteServicePage <</pool-management/dismiss-jurors/dismiss-complete-service>>
participant GenericErrorPage <</error>>

''' CONTROLLER AND REQUEST OBJECTS
participant PoolManagementController <<pool-management.controller.js>>
participant DismissJurorsController <<dismiss-jurors.controller.js>>
participant DismissablePoolsObject <<getDismissablePools.get()>>
participant GetJurorsObject <<getJurorsObject.post()>>
participant JurorAttendanceObject <<jurorAttendanceDao.post()>>
participant UpdateJurorAttendanceObject <<updateJurorAttendanceDAO.patch()>>
participant DismissJurorsObject <<dismissJurorsObject.patch()>>


''' TEMPLATES
participant PoolManagementTemplate <<pool-management/index.njk>>
participant DismissJurorsPoolsTemplate <<pool-management/dismiss-jurors/pools-list.njk>>
participant DismissJurorsSelectTemplate <<pool-management/dismiss-jurors/select-jurors.njk>>
participant CheckOutJurorsTemplate <<pool-management/dismiss-jurors/check-out.njk>>
participant CompleteServiceTemplate <<pool-management/dismiss-jurors/complete-service.njk>>
participant ErrorTemplate <<_errors/generic.njk>>

''' FILTERS AND VALIDATORS
participant JurorsToDismissValidator
participant CheckOutTimeValidator
participant CompleteServiceValidator

''' BACKEND CONTROLLER
participant BackendController


''' JOURNEY FLOW
Actor -> PoolManagementPage : Click 'Dismiss Jurors' tab
PoolManagementPage -> DismissJurorsController : call page controller

$genericAPICall(DismissJurorsController, DismissablePoolsObject, ErrorTemplate, "Failed to fetch pools to dismiss jurors from")
$renderTemplateToPage(DismissJurorsController, DismissJurorsPoolsTemplate, DismissJurorsPoolsPage)

Actor -> DismissJurorsPoolsPage : Select juror types and pools, click 'Calculate available jurors'
DismissJurorsPoolsPage -> DismissJurorsController : call page controller
$genericAPICall(DismissJurorsController, DismissablePoolsObject, ErrorTemplate, "Failed to fetch pools to dismiss jurors from")
$renderTemplateToPage(DismissJurorsController, DismissJurorsPoolsTemplate, DismissJurorsPoolsPage)

Actor -> DismissJurorsPoolsPage : Enter number of jurors to dismiss and click 'Generate list...'
DismissJurorsPoolsPage -> DismissJurorsController : call page controller
$validateInput(DismissJurorsController, JurorsToDismissValidator, DismissJurorsPoolsTemplate, DismissJurorsPoolsPage)

$genericAPICall(DismissJurorsController, GetJurorsObject, ErrorTemplate, "Failed to fetch jurors to dismiss")
$renderTemplateToPage(DismissJurorsController, DismissJurorsSelectTemplate, DismissJurorsSelectPage)

Actor -> DismissJurorsSelectPage : Select jurors to dismiss and click 'Dismiss selected jurors'
DismissJurorsSelectPage -> DismissJurorsController : call page controller
$validateInput(DismissJurorsController, JurorsToDismissValidator, DismissJurorsSelectTemplate, DismissJurorsSelectPage)

$genericAPICall(DismissJurorsController, JurorAttendanceObject, ErrorTemplate, "Failed to fetch juror attendance")

alt some jurors are not checked out
  $renderTemplateToPage(DismissJurorsController, CheckOutJurorsTemplate, CheckOutJurorsPage)
  Actor -> CheckOutJurorsPage : Enter check out time and click 'Continue'
  CheckOutJurorsPage -> DismissJurorsController : call page controller
  $validateInput(DismissJurorsController, CheckOutTimeValidator, CheckOutJurorsTemplate, CheckOutJurorsPage)
  $callAPIRenderErrorOnForm(DismissJurorsController, UpdateJurorAttendanceObject, ErrorTemplate, "Failed to checkout the selected juror", CheckOutJurorsTemplate, CheckOutJurorsPage)
end

$renderTemplateToPage(DismissJurorsController, CompleteServiceTemplate, CompleteServicePage)

Actor -> CompleteServicePage : Enter completion date and click 'Complete service'
$validateInput(DismissJurorsController, CompleteServiceValidator, CompleteServiceTemplate, CompleteServicePage)

alt entered date is before the latest service start date
  $renderErrorOnForm(DismissJurorsController, CompleteServiceTemplate, CompleteServicePage)
end

$callAPIRenderErrorOnForm(DismissJurorsController, DismissJurorsObject, ErrorTemplate, "Failed to dismiss the selected jurors", CompleteServiceTemplate, CompleteServicePage)

PoolManagementController <- DismissJurorsController : redirect to pool management
PoolManagementPage <- PoolManagementController : redirect to pool management
Actor <- PoolManagementPage : render pool management page with success banner

@enduml