@startuml excusal-mod

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant ProcessReplyPage <</process>>
participant ExcusalPage <</excusal>>
participant SummonsInboxPage <</inbox>>
participant SendLetterPage <<custom-components/letter-flow/send-letter>>
participant RedirectPage <<custom-components/letter-flow/redirect>>


''' CONTROLLER AND REQUEST OBJECTS
participant SummonsManagementController <<summons-management.controller.js>>
participant LetterFlow <<letter-flow.js>>
participant ExcusalCodesObject <<excusal.get()>>
participant ExcusalObject <<excusalObject.put()>>
participant InboxController <<inbox.controller.js>>

''' TEMPLATES
participant ExcusalTemplate <<summons-management/excusal.njk>>
participant SendLetterTemplate <<custom-components/letter-flow/send-letter.njk>>
participant RedirectTemplate <<custom-components/letter-flow/redirect.njk>>

''' FILTERS AND VALIDATORS
participant ExcusalValidator

''' BACKEND CONTROLLER
participant BackendController



''' JOURNEY FLOW
Actor -> ProcessReplyPage : grant or refuse excusal

ProcessReplyPage -> SummonsManagementController : call page controller

SummonsManagementController -> ExcusalCodesObject : build request object
ExcusalCodesObject -> BackendController : send backend request
ExcusalCodesObject <- BackendController : ok response
SummonsManagementController <- ExcusalCodesObject : resolve request

SummonsManagementController -> ExcusalTemplate : request and build template
SummonsManagementController <- ExcusalTemplate : return HTML
ExcusalPage <- SummonsManagementController : return HTML
Actor <- ExcusalPage : render HTML

alt Failed to retrieve excusal codes
    ExcusalCodesObject <-- BackendController : error response
    SummonsManagementController <-- ExcusalCodesObject : reject requestObject
    ProcessReplyPage <-- SummonsManagementController : redirect to process reply page
    Actor <-- ProcessReplyPage : redirect to process reply page
end

Actor -> ExcusalPage : enter excusal reason and decision

ExcusalPage -> SummonsManagementController : call page controller

SummonsManagementController -> ExcusalValidator : validate reason and decision
SummonsManagementController <- ExcusalValidator : reason and decision are valid

alt Excusal reason or decision is invalid or missing
    SummonsManagementController <-- ExcusalValidator : reason or decision is invalid or missing
    ExcusalPage <-- SummonsManagementController : error response
    Actor <-- ExcusalPage : render error message
end

SummonsManagementController -> ExcusalObject : build request object
ExcusalObject -> BackendController : send backend request
ExcusalObject <- BackendController : ok response
SummonsManagementController <- ExcusalObject : resolve request

SummonsManagementController -> LetterFlow : request and build template
LetterFlow <- SendLetterTemplate : return HTML
SendLetterPage <- LetterFlow : return HTML
Actor <- SendLetterPage : render HTML

Actor -> SendLetterPage : select yes or no

alt select yes
SendLetterPage -> SummonsManagementController : call page controller
SummonsManagementController -> LetterFlow : request and build template
LetterFlow -> RedirectTemplate : request and build template
RedirectTemplate -> RedirectPage : request and build template
RedirectPage -> SummonsManagementController : call page controller
SummonsManagementController -> InboxController : redirect to inbox
SummonsInboxPage <- InboxController : redirect to inbox
Actor <- SummonsInboxPage : redirect to inbox
end

SendLetterPage -> SummonsManagementController : call page controller
SummonsManagementController -> LetterFlow : redirect to inbox


SummonsManagementController -> InboxController : redirect to inbox
SummonsInboxPage <- InboxController : redirect to inbox
Actor <- SummonsInboxPage : redirect to inbox

alt Failed to process excusal
    ExcusalObject <-- BackendController : error response
    SummonsManagementController <-- ExcusalObject : reject requestBody
    ExcusalPage <-- SummonsManagementController : error response
    Actor <-- ExcusalPage : render error message
end

@enduml