@startuml pool-history
hide unlinked
!include generic-blocks.plantuml

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant PoolManagementPage <<pool-management>>
participant PoolOverviewPage <</pool-management/pool-overview/:poolNumber>>
participant PoolHistoryPage <</pool-management/pool-overview/:poolNumber/history>>
participant GenericErrorPage <</error>>

''' CONTROLLER AND REQUEST OBJECTS
participant PoolManagementController <<pool-management.controller.js>>
participant PoolOverviewController <<pool-overview.controller.js>>
participant PoolSummaryObject <<poolSummaryObj.get()>>
participant PoolHistoryObject <<poolHistoryObj.get()>>


''' TEMPLATES
participant PoolManagementTemplate <<pool-management/index.njk>>
participant PoolOverviewTemplate <<pool-management/pool-overview/{bureau/court}-pool-overview.njk>>
participant ErrorTemplate <<_errors/generic.njk>>

''' FILTERS AND VALIDATORS

''' BACKEND CONTROLLER
participant BackendController


''' JOURNEY FLOW
Actor -> PoolOverviewPage : Click 'history' tab on pool overview page
PoolOverviewPage -> PoolOverviewController : call page controller

$callAPIRenderErrorOnForm(PoolOverviewController, PoolSummaryObject, ErrorTemplate, "Failed to fetch pool summary", PoolManagementTemplate, PoolManagementPage)

$callAPIRenderErrorOnForm(PoolOverviewController, PoolHistoryObject, ErrorTemplate, "Failed to fetch pool history", PoolManagementTemplate, PoolManagementPage)

$renderTemplateToPage(PoolOverviewController, PoolOverviewTemplate, PoolHistoryPage)

@enduml