@startuml pool-search
hide unlinked
!include generic-blocks.plantuml

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant PoolManagementPage <<pool-management>>
participant PoolSearchPage <<pool-management/search>>

''' CONTROLLER AND REQUEST OBJECTS
participant PoolSearchController <<pool-search.controller.js>>
participant PoolSearchObject <<PoolSearchObject.post()>>
participant FetchCourtsObject <<FetchCourts.get()>>

''' TEMPLATES
participant PoolSearchTemplate <<pool-management/pool-search/index.njk>>

''' FILTERS AND VALIDATORS
participant SearchValidator

''' BACKEND CONTROLLER
participant BackendController


''' JOURNEY FLOW
Actor -> PoolManagementPage : user clicks 'Search' tab

PoolManagementPage -> PoolSearchController : call page controller

$genericAPICall(PoolSearchController, FetchCourtsObject, GenericErrorTemplate, "Could not fetch courts")

$genericAPICall(PoolSearchController, PoolSearchObject, GenericErrorTemplate, "Failed to do a pool search")

$renderTemplateToPage(PoolSearchController, PoolSearchTemplate, PoolSearchPage)

Actor -> PoolSearchPage : Enter search details and submit form
PoolSearchPage -> PoolSearchController : call form controller
$validateInput(PoolSearchController, SearchValidator, PoolSearchTemplate, PoolSearchPage)
$genericAPICall(PoolSearchController, PoolSearchObject, GenericErrorTemplate, "Failed to do a pool search")

$renderTemplateToPage(PoolSearchController, PoolSearchTemplate, PoolSearchPage)

@enduml