@startuml reports.pool-ratio

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant "Pool ratio form page" as PoolRatioFormPage <</reporting/pool-ratio>>

''' CONTROLLER AND REQUEST OBJECTS
participant "Pool ratio controller" as PoolRatioController <<pool-ratio.controller.js>> #LightYellow
participant "Courts list" as CourtsList <<courts-list>> #LightYellow
participant "Standard report controller" as StandardReportController <<standard-report.controller.js>> #LightYellow

''' TEMPLATES
participant "Standard report" as StandardReport <<reporting/standard-reports/standard-report.njk>> #lavender

''' VALIDATORS
participant "'Pool ratio' validator" as Validator

''' SELECT PAGE
Actor -> PoolRatioFormPage : fill form and submit
PoolRatioFormPage -> PoolRatioController : call page controller
PoolRatioController -> Validator : validate form data

alt Invalid form data

  PoolRatioController <- Validator : invalid form data
  PoolRatioController -> PoolRatioFormPage : request and build template
  PoolRatioController <- PoolRatioFormPage : return HTML
  Actor <- PoolRatioController : return and render HTML with error messages

end
|||

PoolRatioController <- Validator : valid form data

PoolRatioController -> CourtsList : request and build template
PoolRatioController <- CourtsList : return HTML
CourtsList -> PoolRatioController : select courts from the list

PoolRatioController -> StandardReportController : redirect to standard report controller

StandardReportController -> StandardReport : request and build template
StandardReportController <- StandardReport : return HTML
Actor <- StandardReportController : report displayed by standard renderer