@startuml update-eligibility

skinparam Style strictuml 
skinparam SequenceMessageAlignment center

participant Actor

''' LOCAL ROUTING
participant SummonsReplyPage <</summons-replies/response/{jurorNumber}>>
participant EligibilityPage <</summons-replies/response/{jurorNumber}/paper/update/eligibility>>
participant GenericErrorPage <</error>>


''' CONTROLLER AND REQUEST OBJECTS
participant EligibilityController <<eligibility.controller.js>> #lightyellow
participant paperReplyObjGet <<paperReplyObj.get()>> #lightyellow
participant summonsUpdateObject <<summonsUpdate.patch()>> #lightyellow

''' TEMPLATES
participant SummonsReplyTemplate <</summons-replies/response/{jurorNumber}.njk>>
participant EligibilityTemplate <</summons-replies/response/{jurorNumber}/paper/update/eligibility.njk>>
participant ErrorTemplate <<_errors/generic.njk>> #lavender


''' BACKEND CONTROLLER
participant BackendController

Actor -> SummonsReplyPage : click add or change
SummonsReplyPage -> EligibilityController : call controller
 
EligibilityController -> paperReplyObjGet : build request object
paperReplyObjGet -> BackendController : send backend request
paperReplyObjGet <- BackendController : ok response
EligibilityController <- paperReplyObjGet : resolve request

EligibilityController -> EligibilityTemplate : request and build template
EligibilityController <- EligibilityTemplate : return HTML
EligibilityPage <- EligibilityController : return HTML
Actor <- EligibilityPage : render HTML

Actor -> EligibilityPage : enter changes and save

EligibilityPage -> EligibilityController : POST details


EligibilityController -> summonsUpdateObject : build request object
summonsUpdateObject -> BackendController : send backend request
summonsUpdateObject <- BackendController : ok response
EligibilityController <- summonsUpdateObject : resolve request - no update to values

alt Unable to fetch the summons details
    paperReplyObjGet <-- BackendController : error response
    EligibilityController <-- paperReplyObjGet : reject requestObject
    EligibilityController -> ErrorTemplate : request and build template
    EligibilityController <- ErrorTemplate : return HTML
    GenericErrorPage <- EligibilityController : return HTML
    Actor <- GenericErrorPage : render error page
end

alt Could not update the summons eligibility details
    summonsUpdateObject <-- BackendController : error response
    EligibilityController <-- summonsUpdateObject : reject requestObject
    EligibilityController -> ErrorTemplate : request and build template
    EligibilityController <- ErrorTemplate : return HTML
    GenericErrorPage <- EligibilityController : return HTML
    Actor <- GenericErrorPage : render error page
end

EligibilityController -> paperReplyObjGet : build request object
paperReplyObjGet -> BackendController : send backend request
paperReplyObjGet <- BackendController : ok response
EligibilityController <- paperReplyObjGet : resolve request
EligibilityController -> SummonsReplyTemplate : request and build template
EligibilityController <- SummonsReplyTemplate : return HTML
SummonsReplyPage <- EligibilityController : return HTML
Actor <- SummonsReplyPage : render HTML
