BEGIN
  DELETE FROM JUROR.PASSWORD;
  DELETE FROM JUROR_DIGITAL.BUREAU_AUTH;
  --
  -- juror responses
  DELETE FROM JUROR.PART_HIST;
  DELETE FROM JUROR.PART_AMENDMENTS;
  DELETE FROM JUROR.PHONE_LOG;
  DELETE FROM JUROR.POOL;
  DELETE FROM JUROR.UNIQUE_POOL;
  DELETE FROM JUROR_DIGITAL.CHANGE_LOG_ITEM;
  DELETE FROM JUROR_DIGITAL.CHANGE_LOG;
  DELETE FROM JUROR_DIGITAL.JUROR_RESPONSE_CJS_EMPLOYMENT;
  DELETE FROM JUROR_DIGITAL.JUROR_RESPONSE_SPECIAL_NEEDS;
  DELETE FROM JUROR_DIGITAL.JUROR_RESPONSE;
  DELETE FROM "JUROR_DIGITAL"."JUROR_RESPONSE_AUD";
  DELETE FROM "JUROR_DIGITAL"."COURT_WHITELIST";
  DELETE FROM JUROR_DIGITAL.STAFF;
  DELETE FROM JUROR_DIGITAL.TEAM;
  DELETE FROM JUROR_DIGITAL.STAFF_JUROR_RESPONSE_AUDIT;
  DELETE FROM JUROR_DIGITAL.STAFF_AUDIT;
  DELETE FROM JUROR.DISQ_LETT;
  DELETE FROM JUROR.EXC_LETT;
  DELETE FROM JUROR.EXC_DENIED_LETT;
  --
  -- standing data
  DELETE FROM JUROR_DIGITAL.APP_SETTINGS;
END;
